# Generated by Django 6.0.1 on 2026-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.IntegerField()),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentMarks', models.IntegerField()),
            ],
        ),
    ]
