# Generated by Django 6.0.1 on 2026-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
