# Generated by Django 6.0.1 on 2026-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.IntegerField()),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeSalary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
